path: /home/
servers:
  listen-together:
    hostname: 127.0.0.1
    port: 22
    username: root
commands:
  ll:
    command: ls
    arguments:
      - path
      - list
  print:
    command: echo
    arguments:
      - string
