path: /home/
servers:
  local-server:
    hostname: 127.0.0.1
    port: 22
    username: root
commands:
  ll:
    command: ls
    arguments:
      - Путь
  print:
    command: echo
    arguments:
      - Первая строка
      - Вторая строка
  # запустится /home/script.sh
  Любое читаемое имя скрипта:
    command: ./script.sh
    arguments:
      - Первый аргумент $1
      - Второй аргумент $2
